name: Ubuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install boost
        run: sudo apt-get install libboost-all-dev
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
        
      - name: install_cmake
        run: pip install cmake

      - name: configure
        run: cmake -BkSpider_BUILD_DIR

      - name: build
        run: cmake --build kSpider_BUILD_DIR -j1

      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"